### ISSUE TITLE
SETTINGS: Settings button and save the settings.

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#324]
## Milestones

- [x] Allow choice of theme and set it.
- [x] When a theme is changed automatically inform R rather than needing the USE button.
- [x] Implement a RESTORE button to restore to factory default theme (Rattle)
- [x] Store theme locally and restore next time starting up Rattle

## Description

New Settings button at the top right button hub between the RESET and ABOUT. The settings will be saved for the future and there is the option to reset to the Rattle defaults.

The settings will be a full app window popup that have various fields to set. The popup could use `showGeneralDialog()` for example, as we use in utils/show_image_dialog.dart`.

## Why

So that the user has configuration options available to suit the user.

## Details

For now, have a single setting:

- [x] Graphics Theme: Default is Rattle, but the user can choose from those available in ggplot2 and ggthemes through a matrix of chips with only one chip able to be chosen at a time, or else a dop down menu. The options will include:
  - [x] Rattle (theme_default_rattle)
  - [x] Default (theme_grey)
  - [x] Economist (theme_economist)
  - [x] Economist White (theme_economist_white)
  - [x] Black and White (theme_bw)
  - [x] Calc (theme_calc)
  - [x] Clean (theme_clean)
  - [x] Dark (theme_dark)
  - [x] Excel
  - [x] Excel New
  - [x] Few
  - [x] Five Thirty Eight
  - [x] Foundation
  - [x] GDocs
  - [x] HC
  etc

On closing the SETTINGS popup the `settings.R` script should be run. All settings should be stored in a provider (the theme default, for example, should be `theme_default_rattle`) and r/source.dart should replace any settings in the `settings.R` script (all upper case strings) with the actual settings values from the provider. The settings should be saved between sessions.

To set the theme setting in `settings.R` it will simply require:

```
theme_rattle <- SETTINGS_GRAPHIC_THEME
```

For a start this is the only line R code in settings.R, and rSource('settings.R') is invoked to change the theme.

**Comment by gjwgit** [comment]
Initial button with Under Development widget has been implemented in dev.

**Comment by gjwgit** [comment]
Would saved_preferences flutter package work for us?

**Comment by junhaow1** [comment]
- [ ]  Rattle

- [ ]   Base
 - [ ]  Black and White
 - [ ]  Calc
 - [ ]  Classic
 - [ ]  Dark
 - [ ]  Economist
 - [ ]  Excel
 - [ ]  Few
 - [ ]  Fivethirtyeight
 - [ ]  Foundation
 - [ ]  Gdocs
 - [x]  Grey
 - [ ]  Highcharts
 - [ ]  IGray
 - [ ]  Light
 - [ ]  Linedraw
- [ ]   Minimal
 - [ ]  Pander
 - [ ]  Solarized
 - [ ]  Stata
 - [ ]  Tufte
 - [ ]  Void
 - [ ]  Wall Street Journal

**Comment by gjwgit** [comment]
Seems to be working well now. Please test/review and then close this PR.
